feat(typing): feature flags to process/emit typingState, also typing timeout
dialogs/api-schema pull request #250
Opened 2020-09-09 13:30 UTC by a23sokolov

2020-09-09 13:45 UTC, andorke commented on docs/feature-flags.schema.json
> +      "type": "boolean",
myb long or  integer?

2020-09-09 14:41 UTC, vagola requested changes

2020-09-09 14:41 UTC, vagola commented on docs/feature-flags.schema.json
> +      "type": "boolean",
Type should be numeric

2020-09-10 09:09 UTC, vagola submitted a review, later dismissed

2020-09-10 14:08 UTC, ostronom requested changes
Давайте еще по онлайнам такую же шнягу

2020-09-10 14:10 UTC, Shunaylov commented on docs/feature-flags.schema.json
> +      "default": true
Для онлайнов тоже нужен фиче-флаг, т.к. они реализованы в рамках одной и той же версии схемы. 
Предлагаю его переименовать, например, на "userStatus" или что-то подобное, на клиенте завяжем на него доступность и тайпингов и онлайнов. 
(Либо добавить ещё один для онлайнов, но, на мой взгляд, лучше первый вариант)

2020-09-10 14:51 UTC, Shunaylov commented
> Давайте еще по онлайнам такую же шнягу

думаю можно сделать один флаг на всё

2020-09-11 08:52 UTC, andorke approved these changes

2020-09-11 09:18 UTC, Shunaylov approved these changes

2020-09-11 09:19 UTC, mnasyrov approved these changes

2020-09-11 09:24 UTC, merged