feat(platform): DP-11144 add notification history flag
dialogs/api-schema pull request #267
Opened 2020-10-19 12:42 UTC by Abbath1349

добавил фича флаг для списка уведомлений

2020-10-19 12:56 UTC, arturtakoev requested changes

2020-10-19 12:56 UTC, arturtakoev commented on docs/feature-flags.schema.json
> +    "notifications.history.isEnable": {
```suggestion
    "notifications.history.isEnabled": {
```

2020-10-19 13:10 UTC, Abbath1349 commented on docs/feature-flags.schema.json
> +    "notifications.history.isEnable": {
fixed

2020-10-19 13:11 UTC, vavanrrrage approved these changes

2020-10-19 13:12 UTC, andorke approved these changes

2020-10-19 13:55 UTC, arturtakoev approved these changes

2020-10-20 07:44 UTC, a23sokolov approved these changes

2020-10-20 07:47 UTC, merged