Feat(miniapps): api for missing updates detection
dialogs/api-schema pull request #278
Opened 2020-10-26 12:56 UTC by dpolshin

API allows clients detect if some of updates were missed.
Server will send clock of previous update with each new update.
If client receives update with _prev_clock_ that does not correspond to previous known update then some of updates are assumed missing and client should request state from timestamp of last known consistent state.

2020-10-27 08:21 UTC, likeanowl approved these changes

2020-10-27 08:31 UTC, ostronom requested changes

2020-10-27 08:31 UTC, ostronom commented on proto/miniappsregistry.proto
> +        APPLIFECYCLE_CREATED  = 0;
UpdateMiniApp_prefix required to avoid enum global scope induced conflicts

2020-10-27 08:31 UTC, ostronom commented on proto/miniappsregistry.proto
> +    int64 prev_clock = 3;
do we need THIS_clock here?

2020-10-27 08:57 UTC, dpolshin commented on proto/miniappsregistry.proto
> +    int64 prev_clock = 3;
Yes.
This this is a clock of previous update, not a previous clock of an app.

2020-10-27 09:00 UTC, dpolshin commented on proto/miniappsregistry.proto
> +        APPLIFECYCLE_CREATED  = 0;
APPLIFECYCLE_ prefix is not enough?
this enum is only used in apps update stream and its values do not clash with any other enum values.

2020-10-29 08:28 UTC, dpolshin commented on proto/miniappsregistry.proto
> +    int64 prev_clock = 3;
could you please elaborate what kind of changes you fancy or any questions left to get over it?

2020-11-05 11:23 UTC, ostronom approved these changes

2020-11-05 14:05 UTC, merged