added messages for highlight data result from search request
dialogs/api-schema pull request #281
Opened 2020-10-30 06:22 UTC by bubuker

2020-10-30 08:09 UTC, bubuker commented
Реализация для подсветки при поиске внутри диалога

2020-11-09 09:04 UTC, oseval requested changes

2020-11-09 09:04 UTC, oseval commented on proto/search.proto
> +    MessageHighlight highlight = 7 [(dlg).log="visible"];
а нельзя просто `repeated string highlight_tokens`?

2020-11-09 09:09 UTC, bubuker commented on proto/search.proto
> +    MessageHighlight highlight = 7 [(dlg).log="visible"];
Вообще можно - так как сейчас раелизовано гибче получается. 
Возможно потребуется каким либо образом расширить информацию возвращаемую.
Вопрос насколько это критично.

2020-11-09 11:01 UTC, bubuker commented on proto/search.proto
> +    MessageHighlight highlight = 7 [(dlg).log="visible"];
Поправил

2020-11-10 10:34 UTC, ostronom requested changes

2020-11-10 10:34 UTC, ostronom commented on proto/search.proto
> +//message HLToken {
надо убрать закомментированный код

2020-11-10 10:35 UTC, ostronom requested changes

2020-11-10 10:35 UTC, ostronom commented on proto/search.proto
> +    // -----------------------------
это зачем?

2020-11-10 10:48 UTC, ostronom approved these changes

2020-11-10 11:04 UTC, Daniyarkadyrbekov commented on proto/search.proto
> +    repeated string highlight_tokens = 7 [(dlg).log="visible"];
напишу тут,
коммиты нужно оформлять в соответствии с http://karma-runner.github.io/4.0/dev/git-commit-msg.html
иначе релиз не соберется автоматом

2020-11-10 12:48 UTC, closed without merging